import { Roboto_Serif, DM_Sans } from "next/font/google";
import "./globals.css";

import Footer from "@/components/footer/Footer";

const roboto_serif = Roboto_Serif({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-roboto-serif",
});
const dm_sans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
});

export const metadata = {
  title: "Cox's It Solution",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto_serif.variable} ${dm_sans.variable}`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
