import Image from "next/image";
import SingleImg from "@/img/single-portfolio.png";
import RecentS1 from "@/img/s1.png";
import RecentS2 from "@/img/s2.png";
import RecentS3 from "@/img/s3.png";
import RecentPorfolio from "@/components/portfolio/Portfolio";
import { BsArrowUpRightCircle } from "react-icons/bs";
import projectUs from "@/img/p1.png";
import projectUs2 from "@/img/p2.png";
import projectUs3 from "@/img/p3.png";

export const metadata = {
  title: "Single Project",
  description: "Generated by create next app",
};

const PorfolioSingle = () => {
  return (
    <main>
      <section className="">
        <Image
          className="w-full max-h-[600px] object-cover object-center"
          src={SingleImg}
          alt="Single Portfolio"
        />

        <div className="max-w-7xl mx-auto px-5 flex flex-wrap md:flex-nowrap gap-10 relative -mt-12">
          <div className="flex-auto bg-black p-5 rounded-2xl">
            <h3 className="text-2xl text-white font-roboto-serif font-medium mb-2">
              Catagory:
            </h3>
            <p className="text-white text-lg font-dm-sans">Cloud solution</p>
          </div>
          <div className="flex-auto bg-black p-5 rounded-2xl">
            <h3 className="text-2xl text-white font-roboto-serif font-medium mb-2">
              Client
            </h3>
            <p className="text-white text-lg font-dm-sans">
              BrightMedia Solutions{" "}
            </p>
          </div>
          <div className="flex-auto bg-black p-5 rounded-2xl">
            <h3 className="text-2xl text-white font-roboto-serif font-medium mb-2">
              Date :
            </h3>
            <p className="text-white text-lg font-dm-sans">August 23, 2023</p>
          </div>
          <div className="flex-auto bg-black p-5 rounded-2xl">
            <h3 className="text-2xl text-white font-roboto-serif font-medium mb-2">
              Location:
            </h3>
            <p className="text-white text-lg font-dm-sans">
              489 Depot Road Midland
            </p>
          </div>
        </div>
      </section>
      <section className="py-24">
        <div className="max-w-7xl mx-auto px-5">
          <article className="mb-10">
            <h4 className="font-roboto-serif text-xl font-semibold text-black mb-3">
              01. The Challenge
            </h4>
            <p className="text-lg text-black">
              When our power of choice is untrammeled and when nothing prevents
              us from being able to do what we like best, every pleasure is to
              be welcomed and every pain avoided. But in certain circumstances
              and owing to the claims of duty or the obligations of business it
              will frequently occur that pleasures have to be repudiated and
              annoyances accepted. The wise man therefore always holds in these
              matters to this principle of selection: he rejects pleasures to
              secure other greater pleasures, or else he endures pains to avoid
              worse pains.
            </p>
          </article>
          <article className="mb-10">
            <h4 className="font-roboto-serif text-xl font-semibold text-black mb-3">
              02. The Solution
            </h4>
            <p className="text-lg text-black mb-5">
              Temporibus autem quibusdam et aut officiis debitis aut rerum
              necessitatibus saepe eveniet ut et voluptates repudiandae sint et
              molestiae non recusandae. Itaque earum rerum hic tenetur a
              sapiente delectus, ut aut reiciendis voluptatibus maiores alias
              consequatur aut perferendis doloribus asperiores repellat.
            </p>
            <p className="text-lg text-black max-w-lg">
              One who avoids a pain that produces no resultant pleasure.
              laborious physical exercise. One who avoids a pain that produces
              no resultant which of us ever undertakes laborious Avoids pleasure
              itself, because it is.
            </p>
          </article>
          <article className="mb-20">
            <h4 className="font-roboto-serif text-xl font-semibold text-black mb-3">
              03. The Result
            </h4>
            <p className="text-lg text-black mb-5">
              Because it is pain, but because occasionally circumstances occur
              in which toil and pain can procure him some great pleasure. To
              take a trivial example, which of us ever undertakes laborious
              physical exercise, except to obtain some advantage from it? But
              who has any right to find fault with a man who chooses to enjoy a
              pleasure that has no annoying consequences, or one who avoids a
              pain that produces no resultant pleasure?
            </p>
            <p className="text-lg text-black">
              When our power of choice is untrammeled and when nothing prevents
              us from being able to do what we like best, every pleasure is to
              be welcomed and every pain avoided. But in certain circumstances
              and owing to the claims of duty or the obligations of business it
              will frequently occur that pleasures have to be repudiated and
              annoyances accepted. The wise man therefore always holds in these
              matters to this principle of selection: he rejects pleasures to
              secure other greater pleasures, or else he endures pains to avoid
              worse pains.
            </p>
          </article>

          <div className="grid md:grid-cols-3 gap-10">
            <Image
              className="w-full h-auto rounded-2xl"
              src={RecentS1}
              alt="Recent Post"
            />
            <Image
              className="w-full h-auto rounded-2xl"
              src={RecentS2}
              alt="Recent Post"
            />
            <Image
              className="w-full h-auto rounded-2xl"
              src={RecentS3}
              alt="Recent Post"
            />
          </div>
        </div>
      </section>
      <section className="pb-24 pt-12">
        <div className="max-w-7xl mx-auto px-5">
          <div className="max-w-[750px] mx-auto text-center mb-14">
            <h2 className="text-4xl leading-normal xl:text-6xl text-black font-semibold font-roboto-serif xl:leading-[1.3]">
              Recent Projects
            </h2>
          </div>
          <div className="grid md:grid-cols-3 gap-10">
            <RecentPorfolio
              imgsrc={projectUs}
              alt="Our Project"
              title="Web UI design"
              des="Creative UI design"
              path="/portfolio"
              icon={<BsArrowUpRightCircle size={28} className=" text-white" />}
            />
            <RecentPorfolio
              imgsrc={projectUs2}
              alt="Our Project"
              title="Web UI design"
              des="Creative UI design"
              path="/portfolio"
              icon={<BsArrowUpRightCircle size={28} className=" text-white" />}
            />
            <RecentPorfolio
              imgsrc={projectUs3}
              alt="Our Project"
              title="Web UI design"
              des="Creative UI design"
              path="/portfolio"
              icon={<BsArrowUpRightCircle size={28} className=" text-white" />}
            />
          </div>
        </div>
      </section>
    </main>
  );
};

export default PorfolioSingle;
